version: '3.7'

services:

   postgres-14:
      build: .
      container_name: postgres-14
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: ${USER_PASSWORD}
         POSTGRES_DB: viewadmin
         PGDATA: /var/lib/postgresql/data/pgdata
      ports:
         - 5432:5432
      volumes:
         - pgdata:/var/lib/postgresql/data/pgdata
volumes:
   pgdata: {}